<a href="https://colab.research.google.com/github/2303a51514/2303a51514-batch-22/blob/main/lab-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
fp=open("example.txt","w")
fp.write("hello,B.Tech students!\n")
fp.write("this is file handling in python.\n")
fp.write("SR University\n")
fp.write("Thrishala")
fp.close()
print("Data written successfully!")

Data written successfully!


In [8]:
file=open("example.txt","r")
content=file.read()
print("file content:\n",content)
file.close()

file content:
 hello,B.Tech students!
this is file handling in python.
SR University
Thrishala


In [10]:
file=open("example.txt","r")
line1=file.readline()
print("first line:",line1)
line2=file.readline()
print("second line:",line2)
line3=file.readline()
print("third line:",line3)
file.close()

first line: hello,B.Tech students!

second line: this is file handling in python.

third line: SR University



In [11]:
file=open("example.txt","r")
lines=file.readlines()
print("list of lines:\n",lines)
file.close()

list of lines:
 ['hello,B.Tech students!\n', 'this is file handling in python.\n', 'SR University\n', 'Thrishala']


In [13]:
file=open("example.txt","a")
file.write("Appending new data...\n")
file.close()

In [14]:
with open("example.txt","r") as fp:
  data=fp.read()
  print(data)

hello,B.Tech students!
this is file handling in python.
SR University
Thrishalaappending new data...
Appending new data...



In [24]:
import csv
with open("data.csv","w",newline="") as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age","City"],["aaa",21,"CSE"],["bbb",20,"ECE"]])
with open("data.csv","r") as file:
    re=csv.reader(file)
    for row in re:
      print(row)

['Name', 'Age', 'City']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [25]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1d array:",arr1)

1d array: [1 2 3 4]


In [30]:
import numpy as np
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print("2d array:\n",arr2)

2d array:
 [[1 2 3 4]
 [5 6 7 8]]


In [31]:
import numpy as np
zero_arr=np.zeros((3,3))
print("zeros array:\n",zero_arr)

zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
import numpy as np
ones_arr=np.ones((2,4))
print("oness array:\n",ones_arr)

oness array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
import numpy as np
range_arr=np.arange(0,10,2)#start,stop,step
print("range array:\n",range_arr)

range array:
 [0 2 4 6 8]


In [35]:
import numpy as np
rand_arr=np.random.rand(3,3)
print("Random array:\n",rand_arr)

Random array:
 [[0.02999075 0.16898821 0.12296701]
 [0.65539615 0.75383244 0.97702857]
 [0.63609252 0.6117405  0.78768203]]


In [36]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("dimensions:",arr.ndim)
print("datatype:",arr.dtype)
print("size:",arr.size)
print("item size:",arr.itemsize)

shape: (2, 3)
dimensions: 2
datatype: int64
size: 6
item size: 8


In [37]:
arr=np.array([10,20,30,40,50])
print("first element:",arr[0])
print("last element:",arr[-1])
print("slice[1:4]:",arr[1:4])
print("every second element:",arr[::2])

first element: 10
last element: 50
slice[1:4]: [20 30 40]
every second element: [10 30 50]


In [39]:
arr2=np.array([[1,2,3],[4,5,6]])
print("element at row1,col2:",arr2[0,1])
print("second row:",arr2[1,:])
print("second column:",arr2[:,1])

element at row1,col2: 2
second row: [4 5 6]
second column: [2 5]


In [40]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("power:",a**2)

addition: [5 7 9]
subtraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]
power: [1 4 9]


In [44]:
arr=np.array([1,2,3,4,5])
print("Sin:",np.sin(arr))
print("Cos:",np.cos(arr))
print("Tan:",np.tan(arr))
print("Log:",np.log([1,np.e,np.e**2]))
print("Exp:",np.exp([1,2]))
print("sqrt:",np.sqrt([1,4,9]))
print("sort:",np.sort(arr))
print("argsort:",np.argsort(arr))
print("argmax:",np.argmax(arr))
print("argmin:",np.argmin(arr))
print("std:",np.std(arr))
print("var:",np.var(arr))
print("cumsum:",np.cumsum(arr))
print("cumprod:",np.cumprod(arr))
print("unique:",np.unique(arr))

Sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
Log: [0. 1. 2.]
Exp: [2.71828183 7.3890561 ]
sqrt: [1. 2. 3.]
sort: [1 2 3 4 5]
argsort: [0 1 2 3 4]
argmax: 4
argmin: 0
std: 1.4142135623730951
var: 2.0
cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]
unique: [1 2 3 4 5]


In [45]:
arr=np.array([[1,2,3],[4,5,6]])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("standard deviation:",np.std(arr))
print("sum along axis 0:",np.sum(arr,axis=0))
print("sum along axis 1:",np.sum(arr,axis=1))


Sum: 21
Mean: 3.5
Max: 6
Min: 1
standard deviation: 1.707825127659933
sum along axis 0: [5 7 9]
sum along axis 1: [ 6 15]


In [46]:
a=np.array([1,2,3])
b=5
print("Add scalar to array:",a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("bordcasted sum:\n",c+d)

Add scalar to array: [6 7 8]
bordcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [48]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("dot product:\n",np.dot(A,B))
print("transpose:\n",A.T)
print("inverse:\n",np.linalg.inv(A))
print("determinent:\n",np.linalg.det(A))

dot product:
 [[19 22]
 [43 50]]
transpose:
 [[1 3]
 [2 4]]
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinent:
 -2.0000000000000004


In [49]:
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
