<a href="https://colab.research.google.com/github/2303a51514/2303a51514-batch-22/blob/main/lab-3.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
scores = np.random.randint(50, 100, size=(4, 4))
print("Test Scores (4x4 array):\n", scores)
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation:", std_dev)
print("Variance:", variance)
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nGlobal Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index)
print("\nSummary:")
print(f"Row means: {row_means}")
print(f"Column means: {col_means}")
print(f"Std Dev: {std_dev:.2f}, Variance: {variance:.2f}")
print(f"Max value {global_max} at {max_index}, Min value {global_min} at {min_index}")

Test Scores (4x4 array):
 [[63 85 79 76]
 [82 79 88 92]
 [91 50 98 55]
 [60 93 66 83]]

Row-wise Means: [75.75 85.25 73.5  75.5 ]
Column-wise Means: [74.   76.75 82.75 76.5 ]

Standard Deviation: 14.115594213493104
Variance: 199.25

Global Max: 98 at index (np.int64(2), np.int64(2))
Global Min: 50 at index (np.int64(2), np.int64(1))

Summary:
Row means: [75.75 85.25 73.5  75.5 ]
Column means: [74.   76.75 82.75 76.5 ]
Std Dev: 14.12, Variance: 199.25
Max value 98 at (np.int64(2), np.int64(2)), Min value 50 at (np.int64(2), np.int64(1))


In [4]:
import numpy as np
image = np.random.randint(0, 256, size=(3, 3, 3))
print("Original Image (3x3x3):\n", image)
red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]
print("\nRed Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
avg_red = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue = np.mean(blue_channel)
print("\nAverage Intensities:")
print(f"Red: {avg_red:.2f}, Green: {avg_green:.2f}, Blue: {avg_blue:.2f}")
brightened = np.clip(image + 50, 0, 255)
print("\nBrightened Image (clipped at 255):\n", brightened)

Original Image (3x3x3):
 [[[ 17 127 195]
  [126 130  67]
  [106 125 177]]

 [[ 60 110  59]
  [230 144   3]
  [178 188  25]]

 [[174 125 177]
  [  4 226 189]
  [218  99  10]]]

Red Channel:
 [[ 17 126 106]
 [ 60 230 178]
 [174   4 218]]
Green Channel:
 [[127 130 125]
 [110 144 188]
 [125 226  99]]
Blue Channel:
 [[195  67 177]
 [ 59   3  25]
 [177 189  10]]

Average Intensities:
Red: 123.67, Green: 141.56, Blue: 100.22

Brightened Image (clipped at 255):
 [[[ 67 177 245]
  [176 180 117]
  [156 175 227]]

 [[110 160 109]
  [255 194  53]
  [228 238  75]]

 [[224 175 227]
  [ 54 255 239]
  [255 149  60]]]
